version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: OnlineBookstore.Api/Dockerfile
    container_name: onlinebookstore-api
    ports:
      - "5000:8080" # Mở cổng 80 trong container ra 5000 trên host
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=bookstore;Username=postgres;Password=123456
    networks:
      - backend

volumes:
  pgdata:


networks:
  backend:
